modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "beltborne_lanterns"
version = "${version}"
displayName = "Beltborne Lanterns"
authors = "oxcodsnet"
description = '''
Adds wearable belt lanterns with configurable lighting and compatibility hooks.
'''
#logoFile = ""

[[dependencies.beltborne_lanterns]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beltborne_lanterns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beltborne_lanterns]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
