modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "beltborne_lanterns"
version = "${version}"
displayName = "Beltborne Lanterns"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.beltborne_lanterns]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beltborne_lanterns]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.beltborne_lanterns]]
#modId = "architectury"
#type = "required"
#versionRange = "[13.0.8,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "beltborne_lanterns.mixins.json"
