modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/0xCoDSnet/Beltborne-Lanterns/issues"
license="${mod_license}"

[[mods]]
modId = "beltborne_lanterns"
version="${version}"
displayName="${mod_name}"
description="${mod_description}"
logoFile = "assets/beltborne_lanterns/icon.png"

[[dependencies.beltborne_lanterns]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beltborne_lanterns]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beltborne_lanterns]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.beltborne_lanterns]]
#modId = "architectury"
#type = "required"
#versionRange = "[13.0.8,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "beltborne_lanterns.mixins.json"
